Backend api
Rydg-Tech/shlf-app pull request #10
Opened 2022-02-25 20:08 UTC by Gluay88

2022-02-25 21:10 UTC, VonTeacher requested changes
Made some comments on requested changes.

2022-02-25 21:10 UTC, VonTeacher commented on app/javascript/api/index.js
> +  }
Let's clean up these empty lines and align the curly braces, etc.

2022-02-25 21:10 UTC, VonTeacher commented on app/javascript/components/App.js
> +    console.log(readBlog());
Always delete `console.log`s and `debugger` statements before pushing. :)

2022-02-25 21:10 UTC, VonTeacher commented on app/javascript/components/App.js
> -        {/* <Particles
Delete comments.

2022-02-25 21:10 UTC, VonTeacher commented on app/javascript/components/pages/BlogEdit.js
> +        {this.state.submitted && <Redirect to={`/blogindex`} />}
This doesn't need to be interpolated, since you are just passing a string.

2022-02-25 21:10 UTC, VonTeacher commented on app/javascript/components/pages/BlogIndex.js
> +
Remove blank spaces, unless there is a need for this formatting.

2022-02-25 21:10 UTC, VonTeacher commented on app/javascript/components/pages/BlogShow.js
> +        {this.state.submitted && <Redirect to={`/blogindex`} />}
`to={`/blogindex`}` does not need to be interpolated, since you are just passing a string.

2022-02-25 21:10 UTC, VonTeacher commented on app/javascript/components/pages/ShlfShow.js
> +    console.log(this.props);
Remove `console.log`s before committing.

2022-02-25 21:10 UTC, VonTeacher commented on public/favicon.ico
> +<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 342.55 256.63"><defs><style>.cls-1{fill:#be202e;}.cls-2{fill:#fff;}.cls-3{fill:#f5eb0d;}</style></defs><path clas
And a blank line to the end of this file.

2022-02-25 21:12 UTC, iameddieyayaya commented on app/javascript/api/index.js
> +    return fetch("http://localhost:3000/blogs")
We can reuse the constant variable here ^

2022-02-28 17:52 UTC, iameddieyayaya commented
Has a lot of similar changes to PR#11. Did this one go stale?

2022-02-28 18:09 UTC, VonTeacher commented
Per @Gluay88 this PR is obsolete and can be deleted.

2022-03-01 18:46 UTC, VonTeacher commented
Closing as obsolete.

2022-03-01 18:46 UTC, closed without merging