Gluay rails
Rydg-Tech/shlf-app pull request #9
Opened 2022-02-24 23:38 UTC by Gluay88

2022-02-24 23:43 UTC, iameddieyayaya reviewed
Overall looks good

2022-02-24 23:43 UTC, iameddieyayaya commented on app/javascript/components/pages/BlogNew.js
> +    de;
^ do you need the debugger here?

2022-02-24 23:52 UTC, iameddieyayaya commented on app/javascript/components/pages/BlogNew.js
>      de;
What about this `de;`?

2022-02-24 23:52 UTC, VonTeacher requested changes
Left some comments on necessary cleanup and some questions to answer.

2022-02-24 23:52 UTC, VonTeacher commented on app/javascript/components/pages/BlogNew.js
> +    debugger;
Remove debug statements before pushing. :)

2022-02-24 23:52 UTC, VonTeacher commented on app/javascript/components/pages/BlogNew.js
> +    de;
Looks like part of a leftover debugger. Please delete.

2022-02-24 23:52 UTC, VonTeacher commented on app/javascript/components/App.js
> +    }).then((response) => response.json().then((payload) => this.readBlog()));
Let's keep method chains consistent. In other places, you start a new line for each `.then`, so consider doing that here.

2022-02-24 23:52 UTC, VonTeacher commented on app/javascript/components/pages/BlogEdit.js
> +        {this.state.submitted && <Redirect to={`/blogindex`} />}
Does this need to be interpolated?

2022-02-25 21:11 UTC, VonTeacher commented
Closing as this PR was identified as obsolete by @Gluay88

2022-02-25 21:11 UTC, closed without merging